#
###################################
# Site wide configuration
####################################
#
title: Cyrill
email: lichunyang@outlook.com
description: Cyrill.
url: https://CoderCYLee.github.io # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

permalink: /:year/:month/:day/:title

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Cyrill
  avatar: cyrill.jpg
  job: "IOS"
  bio: "Cyrill."
  email: lichunyang@outlook.com
  disqus-shortname:
  twitter: pennyberry01 #username
  facebook: #username
  google:
    plus:  #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: CoderCYLee #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

